- name: Deploy an App Engine app
  'on':
    push:
      branches:
        - main
  id: deploy-app
  uses: google-github-actions/deploy-appengine@v0.1.0
  with:
    project: ${{ secrets.gcp_project }}
    deliverables: path/to/app.yaml
    credentials: ${{ secrets.gcp_credentials }}